### ISSUE TITLE
I am unable to run notebook file!!!!!

### ISSUE THREAD

**Issue by Isaadahmed2** [rbg-research/Floor-Plan-Detection#3]
IndexError: invalid index to scalar variable.

I am getting this error when I try to run model code
Can you please the requirements file for that.

**Comment by MatteoMaske** [comment]
In the lines which gives you the error delete "[0]" in the wall_width variable assignment. I think in the recent libraries stast.mode(widths) in the mode attribute has only one element and not a list or a tuple

**Comment by Isaadahmed2** [comment]
can you send me the requirements.txt file and the python version

**Comment by MatteoMaske** [comment]
I'm using python 3.11.8 and I installed the recent libraries needed without using any specific version
